### ISSUE TITLE
daemon.log full

### ISSUE THREAD

**Issue by huwylphi** [nDenerserve/node-red-smartpi#1]
Hi,

I'm using _node-red-smartpi_ to read the Smartpi values and publish them over MQTT with a custom payload.
Everything works great except that node-red is filling up the _/var/log/daemon.log_ file.

I tried to disable logging in the _/home/smartpi/.node-red/settings.js_ file but after restarting the node-red service, I can still see new entries every seconds like:

_Feb  8 11:16:19 smartpi Node-RED[505448]: Values: 2023-02-08 11:16:19,0,0,0,0,240,240,240,0,0,0,1,1,1,50.039093041438626,49.951219512195124,49.96096799375488,0,0,0,0,0,0,0,_

The _tmpfs_ filesystem where _/var/log_ in mounted on is set to 50MB and is full very quickly.
How can I disable such logging?

**Comment by nD-enerserve** [comment]
Hi,

I have removed the console.log outputs in node-red nodes.
Try the new version from: 
***@***.***/node-red-smartpi


Mit freundlichen Grüßen
Jens Ramhorst
_______________________________
nD-enerserve GmbH
Max-von-Laue-Str. 19
30966 Hemmingen
Fon: +49 511 47 30 81 45
Fax: +49 511 47 30 81 48
***@***.***
Internet:www.enerserve.eu
USt.-IdNr.: DE303591409
Sitz der Gesellschaft: Hannover
Registergericht: Amtsgericht Hannover, HRB 213079
Geschäftsführer: Dipl.-Ing. Jens Ramhorst, Dipl.-Ing. Clemens Köbe

Am 08.02.23 um 11:21 schrieb Philippe Huwyler:

**Comment by huwylphi** [comment]
Hello,

thanks for that quick response.
I just updated to version 0.1.7 and can confirm that these logs are not written to the daemon.log file anymore.
You can close the issue if you wish, many thanks 👍 

PS:
1. my node-red flow is intended for [home-assistant](https://www.home-assistant.io/) with MQTT auto-discovery. See following snapshot:
![image](https://user-images.githubusercontent.com/3155226/217540416-4ad5596d-a36e-4d68-9f34-f33aeac9bf96.png)

Maybe I could share that example somehow since I think it might help other people using home-assistant?

2. while implementing that flow, I noticed that the consume counter and produce counter respectively from the files _/var/smartpi/consumecounter_ and _/var/smartpi/producecounter_ were not available nor in the _smartpi-values_ nor in the _smartpi-input_. So I added a _watch_ on these files and read the content when the file changed, then join the value in my final payload to publish. 
Would it make sens that, instead of manually reading the files, rather include these two values / logic in the existing _smartpi-values_ and _smartpi-input_?

3. other missing values are _power-total_ and _current-total_ not included in the _smartpi-values_

**Comment by nD-enerserve** [comment]
Hello Philippe,

if that's OK, send me the example. I would then put it here on Github.


Regarding the counters, I'll take this as a suggestion for improvement. 
I will also integrate the other values.

Mit freundlichen Grüßen
Jens Ramhorst
_______________________________
nD-enerserve GmbH
Max-von-Laue-Str. 19
30966 Hemmingen
Fon: +49 511 47 30 81 45
Fax: +49 511 47 30 81 48
***@***.***
Internet:www.enerserve.eu
USt.-IdNr.: DE303591409
Sitz der Gesellschaft: Hannover
Registergericht: Amtsgericht Hannover, HRB 213079
Geschäftsführer: Dipl.-Ing. Jens Ramhorst, Dipl.-Ing. Clemens Köbe

Am 08.02.23 um 14:22 schrieb Philippe Huwyler:

**Comment by huwylphi** [comment]
Hi Jens,

that's great! So once the other values are included, probably we can simplify the node-red flow.

Find my current flow.json in the attachment

[flows.zip](https://github.com/nDenerserve/node-red-smartpi/files/10686079/flows.zip)

Edit: I've replaced the flow.zip file by anonymizing some MQTT connection string...

**Comment by nD-enerserve** [comment]
I have added
p total, i total, ep total, ec total.

There is now a subdirectory examples, where examples and exampleflows are collected.

**Comment by huwylphi** [comment]
Hi,

this is nice, thanks. I've updated the home assistance node-red flow example to work with v0.2.4:
- simplified node-red flow by removing fetching of single values for p total and i total since now included in all values
- included ep total and ec total in MQTT published payload

This is included in the [PR#2](https://github.com/nDenerserve/node-red-smartpi/pull/2)

Kind regards
